# [[language]]
# name = "java"
# scope = "source.java"
# injection-regex = "java"
# file-types = ["java"]
# roots = ["pom.xml"]
# language-server = { command = "jdtls", args =[
#     # "-Declipse.application=org.eclipse.jdt.ls.core.id1",
#     # "-Dosgi.bundles.defaultStartLevel=4",
#     # "-Declipse.product=org.eclipse.jdt.ls.core.product",
#     # "-Dlog.protocol=true",
#     # "-Dlog.level=ALL",
#     # "-Xms1g",
#     # "--add-modules=ALL-SYSTEM",
#     # "--add-opens",
#     # "java.base/java.util=ALL-UNNAMED",
#     # "--add-opens",
#     # "java.base/java.lang=ALL-UNNAMED",
#     # # "-javaagent:/path/to/lombok.jar",
#     # # "-Xbootclasspath/a:/path/to/lombok.jar",
#     # "-jar",
#     # "/usr/local/Cellar/jdtls/1.15.0/libexec/plugins/org.eclipse.equinox.launcher_1.6.400.v20210924-0641.jar",
#     "-configuration",
#     "/usr/local/Cellar/jdtls/1.15.0/libexec/config_mac",
#     "-data",
#     "/Users/ghar/.cache/jdtls-workspace"
#     ]}
# indent = { tab-width = 4, unit = "    " }
#
# [[grammar]]
# name = "java"
# source = { git = "https://github.com/tree-sitter/tree-sitter-java", rev = "bd6186c24d5eb13b4623efac9d944dcc095c0dad" }
